#!/bin/bash
set -euo pipefail

# Change directory to the root of the project
cd "$(dirname "$0")/.."

VCODEC=libx264
COLOR=bt709
FPS=30

video_size="1280x720"
INPUT="-f lavfi -re -i testsrc=s=$video_size:r=$FPS"
PUT_TIMESTAMP="${put_timestamp:-0}"
FONT_PATH="${font_path:-/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf}"
TS_FORMAT="${ts_format:-%T.%3N}"
VIDEO_FILTER="drawtext=fontfile='$FONT_PATH':fontsize=80:box=1:boxborderw=4:boxcolor=black@0.6:fontcolor=white:x=32:y=H-80:text='T0\: %{localtime\:$TS_FORMAT}'[time];"
res="1280x720"
bitrate="3000000"
bufsize="6M"
gop_size=$FPS

# Use debug logging by default
export RUST_LOG="${RUST_LOG:-debug}"

# Connect to localhost by default.
#HOST="moq-test.logic-services.de"
HOST="${HOST:-localhost}"
PORT="${PORT:-4443}"
ADDR="${ADDR:-$HOST:$PORT}"
SCHEME="${SCHEME:-https}"

# Use the name "bbb" for the broadcast.
# NAME="${NAME:-bbb}"
NAME="dev"

# Combine the host into a URL.
URL="${URL:-"$SCHEME://$ADDR"}"

# Default to a source video
INPUT="${INPUT:-dev/bbb.fmp4}"

# Print out the watch URL
echo "Watch URL: https://quic.video/watch/$NAME?server=$ADDR"

# Run ffmpeg and pipe the output to moq-pub

# Run ffmpeg from moq-vs-dash
ffmpeg -hide_banner -probesize 10M $INPUT -an -fflags nobuffer \
		-f mp4 -c:v $VCODEC -movflags cmaf+separate_moof+delay_moov+skip_trailer -x264-params "nal-hrd=cbr" \
		-map 0 \
		-s:v:0 ${res} -b:v:0 ${bitrate} -minrate ${bitrate} -maxrate ${bitrate} -bufsize ${bufsize} \
		-vf "$VIDEO_FILTER" \
		-g:v $gop_size -keyint_min:v $gop_size -sc_threshold:v 0 -streaming 1 -tune zerolatency \
		-color_primaries ${COLOR} -color_trc ${COLOR} -colorspace ${COLOR} \
		-frag_type duration -frag_duration 1 - | \
		tee >(ffplay -fflags nobuffer -flags low_delay -probesize 32 -framedrop -sync ext -) | cargo run --bin moq-pub -- --tls-disable-verify --name "$NAME" "$URL" "$@"
